//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tawaco2Entities : DbContext
    {
        public tawaco2Entities()
            : base("name=tawaco2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Accreditation_Types> t_Accreditation_Types { get; set; }
        public virtual DbSet<t_Accreditations> t_Accreditations { get; set; }
        public virtual DbSet<t_Alarm_Configurations> t_Alarm_Configurations { get; set; }
        public virtual DbSet<t_Alarms> t_Alarms { get; set; }
        public virtual DbSet<t_Channel_Configurations> t_Channel_Configurations { get; set; }
        public virtual DbSet<t_Consumers> t_Consumers { get; set; }
        public virtual DbSet<t_Data_Complexes> t_Data_Complexes { get; set; }
        public virtual DbSet<t_Data_Raw_Indexes> t_Data_Raw_Indexes { get; set; }
        public virtual DbSet<t_DisplayGroups> t_DisplayGroups { get; set; }
        public virtual DbSet<t_Language> t_Language { get; set; }
        public virtual DbSet<t_LanguageTranslate> t_LanguageTranslate { get; set; }
        public virtual DbSet<t_Logger_Configurations> t_Logger_Configurations { get; set; }
        public virtual DbSet<t_Logger_Files> t_Logger_Files { get; set; }
        public virtual DbSet<t_Logger_Histories> t_Logger_Histories { get; set; }
        public virtual DbSet<t_Loggers> t_Loggers { get; set; }
        public virtual DbSet<t_Meter_Files> t_Meter_Files { get; set; }
        public virtual DbSet<t_Meter_Histories> t_Meter_Histories { get; set; }
        public virtual DbSet<t_Meters> t_Meters { get; set; }
        public virtual DbSet<t_RoleFunction> t_RoleFunction { get; set; }
        public virtual DbSet<t_Roles> t_Roles { get; set; }
        public virtual DbSet<t_Site_Files> t_Site_Files { get; set; }
        public virtual DbSet<t_Sites> t_Sites { get; set; }
        public virtual DbSet<t_Staffs> t_Staffs { get; set; }
        public virtual DbSet<t_SysParam> t_SysParam { get; set; }
        public virtual DbSet<t_Transmitter_Files> t_Transmitter_Files { get; set; }
        public virtual DbSet<t_Transmitter_Histories> t_Transmitter_Histories { get; set; }
        public virtual DbSet<t_Transmitters> t_Transmitters { get; set; }
        public virtual DbSet<t_Units> t_Units { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
        public virtual DbSet<t_Site_Availabilities> t_Site_Availabilities { get; set; }
    
        public virtual int CustomSearch(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomSearch", searchParameter);
        }
    
        public virtual int DataInsert(string tName)
        {
            var tNameParameter = tName != null ?
                new ObjectParameter("TName", tName) :
                new ObjectParameter("TName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataInsert", tNameParameter);
        }
    
        public virtual int DataXMLInsert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataXMLInsert");
        }
    
        public virtual int DataXMLInsert_Softrel(string validXMLInput, string tablename)
        {
            var validXMLInputParameter = validXMLInput != null ?
                new ObjectParameter("ValidXMLInput", validXMLInput) :
                new ObjectParameter("ValidXMLInput", typeof(string));
    
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataXMLInsert_Softrel", validXMLInputParameter, tablenameParameter);
        }
    
        public virtual int p_ComplexData_Select_Faster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_Faster");
        }
    
        public virtual int p_ComplexData_Select_For_Consumer(string consumerId)
        {
            var consumerIdParameter = consumerId != null ?
                new ObjectParameter("ConsumerId", consumerId) :
                new ObjectParameter("ConsumerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Consumer", consumerIdParameter);
        }
    
        public virtual int p_ComplexData_Select_For_Site(string siteId)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Site", siteIdParameter);
        }
    
        public virtual int p_ComplexData_Select_For_Staff(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Staff", staffIdParameter);
        }
    
        public virtual int p_Create_Data_Table(string channelId)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Create_Data_Table", channelIdParameter);
        }
    
        public virtual int p_Data_Logger_Get(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Get", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Drop_Data_Table(string channelId)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Drop_Data_Table", channelIdParameter);
        }
    
        public virtual int p_Index_Logger_Get(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Index_Logger_Get", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Press_Get(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Get", startParameter, endParameter);
        }
    
        public virtual int p_Press_Get_2015(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Get_2015", startParameter, endParameter);
        }
    
        public virtual int p_Press_Getw(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Getw", startParameter, endParameter);
        }
    
        public virtual int ProductsAccessXMLInsertDataComplex(string validXMLInput)
        {
            var validXMLInputParameter = validXMLInput != null ?
                new ObjectParameter("ValidXMLInput", validXMLInput) :
                new ObjectParameter("ValidXMLInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductsAccessXMLInsertDataComplex", validXMLInputParameter);
        }
    }
}
