//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Accreditations
    {
        public string AccreditationDocument { get; set; }
        public string MeterSerial { get; set; }
        public string TransmitterSerial { get; set; }
        public string AccreditationType { get; set; }
        public System.DateTime AccreditationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Description { get; set; }
    
        public virtual t_Accreditation_Types t_Accreditation_Types { get; set; }
        public virtual t_Meters t_Meters { get; set; }
        public virtual t_Transmitters t_Transmitters { get; set; }
    }
}
