//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Alarm_Configurations
    {
        public int Id { get; set; }
        public string SiteId { get; set; }
        public string PhoneNr { get; set; }
        public Nullable<bool> Ena1 { get; set; }
        public Nullable<bool> Ena2 { get; set; }
        public Nullable<bool> Ena3 { get; set; }
        public Nullable<bool> Ena4 { get; set; }
        public Nullable<bool> Ena { get; set; }
        public string Note { get; set; }
    }
}
