//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Data_Complexes
    {
        public string LoggerId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<double> ForwardFlow { get; set; }
        public Nullable<double> ReverseFlow { get; set; }
        public Nullable<double> ForwardIndex { get; set; }
        public Nullable<double> ReverseIndex { get; set; }
        public Nullable<double> Pressure1 { get; set; }
        public Nullable<double> Pressure2 { get; set; }
        public Nullable<double> MinForwardFlow { get; set; }
        public Nullable<double> MaxForwardFlow { get; set; }
        public Nullable<double> MinReverseFlow { get; set; }
        public Nullable<double> MaxReverseFlow { get; set; }
        public Nullable<double> MinPressure1 { get; set; }
        public Nullable<double> MaxPressure1 { get; set; }
        public Nullable<double> MinPressure2 { get; set; }
        public Nullable<double> MaxPressure2 { get; set; }
    
        public virtual t_Logger_Configurations t_Logger_Configurations { get; set; }
    }
}
