//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Data_Manual
    {
        public int Stt { get; set; }
        public string SiteId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> Index { get; set; }
        public Nullable<double> Output { get; set; }
        public string Description { get; set; }
    }
}
