//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Devices_Loggers
    {
        public string Serial { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Provider { get; set; }
        public string Marks { get; set; }
        public string Model { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Installed { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAccreditation { get; set; }
        public Nullable<System.DateTime> DateInstallBattery { get; set; }
        public Nullable<int> YearBattery { get; set; }
    }
}
