//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Devices_ChannelsConfigs
    {
        public string Id { get; set; }
        public string LoggerId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> LastTimeStamp { get; set; }
        public Nullable<double> LastValue { get; set; }
        public string Description { get; set; }
        public Nullable<double> BaseMin { get; set; }
        public Nullable<double> BaseMax { get; set; }
        public Nullable<double> BaseLine { get; set; }
        public string GroupChannel { get; set; }
        public Nullable<bool> Pressure1 { get; set; }
        public Nullable<bool> Pressure2 { get; set; }
        public Nullable<bool> ForwardFlow { get; set; }
        public Nullable<bool> ReverseFlow { get; set; }
        public Nullable<bool> DisplayOnGraph { get; set; }
        public Nullable<bool> StatusViewAlarm { get; set; }
    }
}
