//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Devices_Meters
    {
        public string Serial { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> AccreditedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string AccreditationDocument { get; set; }
        public string AccreditationType { get; set; }
        public string Provider { get; set; }
        public string Marks { get; set; }
        public Nullable<short> Size { get; set; }
        public string Model { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Installed { get; set; }
        public Nullable<double> InitialIndex { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovalDecision { get; set; }
        public string SerialTransmitter { get; set; }
        public string Nationality { get; set; }
    }
}
