//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_History_Sites
    {
        public string SiteId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Meter { get; set; }
        public string SerialMeter { get; set; }
        public Nullable<bool> Transmitter { get; set; }
        public string SerialTransmitter { get; set; }
        public Nullable<bool> Logger { get; set; }
        public string SeriLogger { get; set; }
        public Nullable<bool> Battery { get; set; }
        public Nullable<bool> TransmitterBattery { get; set; }
        public Nullable<bool> LoggerBattery { get; set; }
        public string Description { get; set; }
        public Nullable<double> Index { get; set; }
    }
}
