//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_History_Site_Transmitters
    {
        public System.DateTime DateChanged { get; set; }
        public string SiteId { get; set; }
        public string OldMeterSerial { get; set; }
        public string NewMeterSerial { get; set; }
        public Nullable<double> OldMeterIndex { get; set; }
        public Nullable<double> NewMeterIndex { get; set; }
        public string Description { get; set; }
    }
}
