//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Logger_Histories
    {
        public int HistoryID { get; set; }
        public string SiteID { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string OldLoggerSerial { get; set; }
        public string NewLoggerSerial { get; set; }
        public Nullable<double> Index { get; set; }
        public string Description { get; set; }
    
        public virtual t_Loggers t_Loggers { get; set; }
        public virtual t_Sites t_Sites { get; set; }
    }
}
