//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Logger_Configurations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Logger_Configurations()
        {
            this.t_Channel_Configurations = new HashSet<t_Channel_Configurations>();
            this.t_Data_Complexes = new HashSet<t_Data_Complexes>();
            this.t_Sites = new HashSet<t_Sites>();
        }
    
        public string LoggerId { get; set; }
        public string SiteId { get; set; }
        public Nullable<byte> StartHour { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<byte> Pressure1 { get; set; }
        public Nullable<byte> Pressure2 { get; set; }
        public Nullable<byte> ForwardFlow { get; set; }
        public Nullable<byte> ReverseFlow { get; set; }
        public Nullable<bool> Alarm { get; set; }
        public Nullable<int> TimeDelayAlarm { get; set; }
        public Nullable<byte> Interval { get; set; }
        public Nullable<bool> Status1 { get; set; }
        public Nullable<bool> Status2 { get; set; }
        public Nullable<int> TimeOffset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Channel_Configurations> t_Channel_Configurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Data_Complexes> t_Data_Complexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Sites> t_Sites { get; set; }
    }
}
