//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Site_Sites
    {
        public string Id { get; set; }
        public string OldId { get; set; }
        public string Location { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string ViewGroup { get; set; }
        public string StaffId { get; set; }
        public string Meter { get; set; }
        public string Transmitter { get; set; }
        public string Logger { get; set; }
        public Nullable<System.DateTime> DateOfMeterChange { get; set; }
        public Nullable<System.DateTime> DateOfLoggerChange { get; set; }
        public Nullable<System.DateTime> DateOfTransmitterChange { get; set; }
        public Nullable<System.DateTime> DateOfBatteryChange { get; set; }
        public Nullable<System.DateTime> DateOfTransmitterBatteryChange { get; set; }
        public Nullable<System.DateTime> DateOfLoggerBatteryChange { get; set; }
        public string DescriptionOfChange { get; set; }
        public Nullable<double> ChangeIndex { get; set; }
        public string Level { get; set; }
        public string Group { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> TakeoverDate { get; set; }
        public Nullable<bool> Takeovered { get; set; }
        public string Status { get; set; }
        public string Availability { get; set; }
        public Nullable<bool> Display { get; set; }
        public Nullable<bool> Property { get; set; }
        public Nullable<bool> UsingLogger { get; set; }
        public string MeterDirection { get; set; }
        public string ProductionCompany { get; set; }
        public string IstDistributionCompany { get; set; }
        public string QndDistributionCompany { get; set; }
        public Nullable<bool> IstDoNotCalculateReverse { get; set; }
        public Nullable<bool> QndDoNotCalculateReverse { get; set; }
        public string Description { get; set; }
        public Nullable<double> ChangeIndex1 { get; set; }
        public string Group2 { get; set; }
        public string Address { get; set; }
        public string CoverID { get; set; }
        public string Group3 { get; set; }
        public string Group4 { get; set; }
        public string Group5 { get; set; }
        public string District { get; set; }
        public string DMAOut { get; set; }
    }
}
