//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Site_Covers
    {
        public string CoverID { get; set; }
        public Nullable<int> CoverL { get; set; }
        public Nullable<int> CoverW { get; set; }
        public Nullable<int> CoverH { get; set; }
        public string CoverMaterial { get; set; }
        public Nullable<int> CoverNL { get; set; }
    }
}
