//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Site_Companies
    {
        public string Company { get; set; }
        public Nullable<bool> Production { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public Nullable<int> AmountDHTKH { get; set; }
        public Nullable<int> AmountValve { get; set; }
        public Nullable<int> AmountPool { get; set; }
        public Nullable<int> AmountTCH { get; set; }
        public Nullable<double> NRW { get; set; }
    }
}
