//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SysParam
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Val { get; set; }
        public string Val2 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public bool Activated { get; set; }
        public string LanguageId { get; set; }
    }
}
