//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Transmitter_Histories
    {
        public int HistoryID { get; set; }
        public string SiteID { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string OldTransmitterSerial { get; set; }
        public string OldAccreditation { get; set; }
        public string NewTransmitterSerial { get; set; }
        public string NewAccreditation { get; set; }
        public Nullable<double> Index { get; set; }
        public string Description { get; set; }
    
        public virtual t_Transmitters t_Transmitters { get; set; }
    }
}
