//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Users
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string StaffId { get; set; }
        public string ConsumerId { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Ip { get; set; }
        public Nullable<int> LoginTime { get; set; }
        public Nullable<int> SetDelayTime { get; set; }
        public Nullable<double> SetDiffValue { get; set; }
        public string Language { get; set; }
    
        public virtual t_Consumers t_Consumers { get; set; }
        public virtual t_Roles t_Roles { get; set; }
        public virtual t_Staffs t_Staffs { get; set; }
    }
}
