//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_User_Users
    {
        public string Uid { get; set; }
        public string StaffId { get; set; }
        public string Pwd { get; set; }
        public string Salt { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Ip { get; set; }
        public Nullable<int> LogCount { get; set; }
        public Nullable<byte> Zoom { get; set; }
        public string Company { get; set; }
        public string Language { get; set; }
    }
}
